# Generated by Django 4.2.7 on 2026-04-25 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_platform', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('OTHER', 'Other')], max_length=30, verbose_name='مصدر الرسالة')),
                ('message_content', models.TextField(verbose_name='نص الرسالة الأصلي')),
                ('sender_identifier', models.CharField(max_length=255, verbose_name='معرف المرسل')),
                ('attachment_url', models.TextField(blank=True, null=True, verbose_name='رابط المرفقات')),
                ('process_status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('FORWARDED', 'تم التحويل'), ('REPLIED', 'تم الرد'), ('DELETED', 'محذوف')], default='PENDING', max_length=30, verbose_name='حالة المعالجة')),
                ('reply_content', models.TextField(blank=True, null=True, verbose_name='نص الرد')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات داخلية')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الوصول')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_actions', to=settings.AUTH_USER_MODEL, verbose_name='متخذ القرار')),
                ('target_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_messages', to='shared_inbox.question', verbose_name='السؤال المرتبط')),
            ],
            options={
                'verbose_name': 'رسالة واردة',
                'verbose_name_plural': 'الرسائل الواردة',
                'ordering': ['-received_at'],
            },
        ),
    ]
