# Generated by Django 4.2.7 on 2026-04-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_inbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القناة/الصفحة')),
                ('platform_identifier', models.CharField(choices=[('YOUTUBE', 'يوتيوب (YouTube)'), ('FACEBOOK', 'فيسبوك (Facebook)'), ('INSTAGRAM', 'انستغرام (Instagram)'), ('TIKTOK', 'تيك توك (TikTok)'), ('WHATSAPP', 'واتساب (WhatsApp)'), ('TELEGRAM', 'تيليجرام (Telegram)'), ('OTHER', 'أخرى (Other)')], max_length=50, verbose_name='نوع المنصة')),
                ('credentials', models.JSONField(blank=True, default=dict, verbose_name='بيانات الربط السرية (Credentials)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قناة تواصل',
                'verbose_name_plural': 'قنوات التواصل المتصلة',
            },
        ),
        migrations.RemoveField(
            model_name='incomingmessage',
            name='source_platform',
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='external_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف الرسالة الخارجي'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='external_parent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف المنشور/الفيديو الخارجي'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='message_type',
            field=models.CharField(choices=[('COMMENT', 'تعليق (Comment)'), ('DIRECT_MESSAGE', 'رسالة خاصة (DM)'), ('MENTION', 'إشارة (Mention)')], default='DIRECT_MESSAGE', max_length=50, verbose_name='نوع الرسالة'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shared_inbox.connectedchannel', verbose_name='القناة المتصلة'),
        ),
    ]
